In [1]:
import polars as pl
import pandas as pd

# Read data from S3

In [2]:
source_bucket = 's3://msds-26.2-data'
file_name_1 = 'inflation_data_north_america_capstone.csv'

## Polars way

In [3]:
file_path_1 = f'{source_bucket}/{file_name_1}'
df_1_polars = pl.read_csv(file_path_1)

In [4]:
df_1_polars

shape: (3, 13)
┌───────────────┬───────┬───────┬───────┬───┬───────┬───────┬───────┬───────┐
│ Country       ┆ 2019  ┆ 2020  ┆ 2021  ┆ … ┆ 2027  ┆ 2028  ┆ 2029  ┆ 2030  │
│ ---           ┆ ---   ┆ ---   ┆ ---   ┆   ┆ ---   ┆ ---   ┆ ---   ┆ ---   │
│ str           ┆ str   ┆ str   ┆ str   ┆   ┆ str   ┆ str   ┆ str   ┆ str   │
╞═══════════════╪═══════╪═══════╪═══════╪═══╪═══════╪═══════╪═══════╪═══════╡
│ Canada        ┆ 1.95% ┆ 0.72% ┆ 3.40% ┆ … ┆ 2.01% ┆ 2.00% ┆ 2.03% ┆ 2.00% │
│ Mexico        ┆ 3.64% ┆ 3.40% ┆ 5.69% ┆ … ┆ 3.01% ┆ 3.00% ┆ 3.00% ┆ 3.00% │
│ United States ┆ 1.81% ┆ 1.25% ┆ 4.68% ┆ … ┆ 2.11% ┆ 2.16% ┆ 2.17% ┆ 2.18% │
└───────────────┴───────┴───────┴───────┴───┴───────┴───────┴───────┴───────┘

## Pandas way

In [5]:
df_1_pandas = pd.read_csv(file_path_1)

In [6]:
df_1_pandas

,Country,2019,2020,2021,2022,2023,2024,2025,2026,2027,2028,2029,2030
0,Canada,1.95%,0.72%,3.40%,6.78%,3.89%,2.40%,1.98%,2.13%,2.01%,2.00%,2.03%,2.00%
1,Mexico,3.64%,3.40%,5.69%,7.90%,5.53%,4.72%,3.54%,3.17%,3.01%,3.00%,3.00%,3.00%
2,United States,1.81%,1.25%,4.68%,7.99%,4.13%,2.95%,2.99%,2.47%,2.11%,2.16%,2.17%,2.18%