In [ ]:
!pip install shap polars optuna optuna-integration interpret

In [1]:
import polars as pl
from IPython.display import HTML

In [2]:
from src.pipeline import Pipeline, Context                                                                                                                                                                                                                                                             
from src.pipeline_steps import Load, Preprocess, TrainBinaryClassifier, TrainRegressor, TrainPerChannelShareRegressors, Predict, Report
from src.config import YEARLY_RECOVERY_DATA_CSV_FPS, S3_BUCKET_URI, S3_BUCKET, MODEL_DIR, CLF_MODEL_S3_KEY, REG_MODEL_S3_KEY, SHARE_MODELS_S3_PREFIX, REPORT_S3_KEY, ContextKeys

In [3]:
ctx = Context() 
Pipeline(
    Load(recovery_data_source=YEARLY_RECOVERY_DATA_CSV_FPS),
    Preprocess(write_to=f"{S3_BUCKET_URI}/data/processed/preprocessed_recovery_data.parquet"),
    TrainBinaryClassifier(read_from_key=CLF_MODEL_S3_KEY),
    TrainRegressor(read_from_key=REG_MODEL_S3_KEY),
    TrainPerChannelShareRegressors(save_to_prefix=SHARE_MODELS_S3_PREFIX),
    Predict(predict_channels=True, run_shap=False),
    Report(top_n=10, save_to=f"{S3_BUCKET_URI}/{REPORT_S3_KEY}")
)(ctx)

In [10]:
df_pre_data = ctx[ContextKeys.DF_RECOVERY_LOADED]

In [11]:
df_pre_data['year'].value_counts()

shape: (4, 2)
┌──────┬──────────┐
│ year ┆ count    │
│ ---  ┆ ---      │
│ i64  ┆ u32      │
╞══════╪══════════╡
│ 2022 ┆ 10902782 │
│ 2025 ┆ 18981023 │
│ 2023 ┆ 11557004 │
│ 2024 ┆ 17414249 │
└──────┴──────────┘

In [12]:
df_post_data = ctx['df_recovery_preprocessed']

In [13]:
df = ctx["predictions"]
df.head()

shape: (5, 28)
┌─────────────┬─────────────┬──────┬──────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ hashed_fc   ┆ gl_product_ ┆ year ┆ week ┆ … ┆ shap_baseli ┆ shap_devia ┆ rate_bucke ┆ volume_buc │
│ ---         ┆ group       ┆ ---  ┆ ---  ┆   ┆ ne_rate     ┆ tion_contr ┆ t          ┆ ket        │
│ str         ┆ ---         ┆ i64  ┆ f64  ┆   ┆ ---         ┆ ibution    ┆ ---        ┆ ---        │
│             ┆ f64         ┆      ┆      ┆   ┆ f64         ┆ ---        ┆ str        ┆ str        │
│             ┆             ┆      ┆      ┆   ┆             ┆ f64        ┆            ┆            │
╞═════════════╪═════════════╪══════╪══════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ 0006a543ece ┆ 60.0        ┆ 2025 ┆ 14.0 ┆ … ┆ NaN         ┆ NaN        ┆ zero       ┆ <10        │
│ ed85f71ee81 ┆             ┆      ┆      ┆   ┆             ┆            ┆            ┆            │
│ 511c9622…   ┆             ┆      ┆      ┆   ┆             ┆            ┆            ┆            │
│ 0006a543ece ┆ 60.0        ┆ 2025 ┆ 15.0 ┆ … ┆ NaN         ┆ NaN        ┆ zero       ┆ <10        │
│ ed85f71ee81 ┆             ┆      ┆      ┆   ┆             ┆            ┆            ┆            │
│ 511c9622…   ┆             ┆      ┆      ┆   ┆             ┆            ┆            ┆            │
│ 0006a543ece ┆ 60.0        ┆ 2025 ┆ 16.0 ┆ … ┆ NaN         ┆ NaN        ┆ zero       ┆ <10        │
│ ed85f71ee81 ┆             ┆      ┆      ┆   ┆             ┆            ┆            ┆            │
│ 511c9622…   ┆             ┆      ┆      ┆   ┆             ┆            ┆            ┆            │
│ 0006a543ece ┆ 60.0        ┆ 2025 ┆ 22.0 ┆ … ┆ NaN         ┆ NaN        ┆ zero       ┆ 10-100     │
│ ed85f71ee81 ┆             ┆      ┆      ┆   ┆             ┆            ┆            ┆            │
│ 511c9622…   ┆             ┆      ┆      ┆   ┆             ┆            ┆            ┆            │
│ 0006a543ece ┆ 60.0        ┆ 2025 ┆ 23.0 ┆ … ┆ NaN         ┆ NaN        ┆ zero       ┆ 10-100     │
│ ed85f71ee81 ┆             ┆      ┆      ┆   ┆             ┆            ┆            ┆            │
│ 511c9622…   ┆             ┆      ┆      ┆   ┆             ┆            ┆            ┆            │
└─────────────┴─────────────┴──────┴──────┴───┴─────────────┴────────────┴────────────┴────────────┘

In [16]:
df.write_parquet(r's3://msds-26.2-data/out/predictions_2025.parquet')

In [14]:
df_post_data['year'].value_counts()

shape: (4, 2)
┌──────┬─────────┐
│ year ┆ count   │
│ ---  ┆ ---     │
│ i64  ┆ u32     │
╞══════╪═════════╡
│ 2025 ┆ 2542216 │
│ 2023 ┆ 2069487 │
│ 2024 ┆ 2349233 │
│ 2022 ┆ 1807934 │
└──────┴─────────┘

In [15]:
df['year'].value_counts()

shape: (1, 2)
┌──────┬─────────┐
│ year ┆ count   │
│ ---  ┆ ---     │
│ i64  ┆ u32     │
╞══════╪═════════╡
│ 2025 ┆ 2542216 │
└──────┴─────────┘